### PR TITLE
[moe_misc] Vectorized version of scatter_output

### PR DESCRIPTION
**Pull request by shtinsa**
The purpose of this PR is a minor optimization of scatter_output kernel required for mixtral models.

### CODE REVIEW

**Comment by sunggg** [comment]
Thanks, @shtinsa! Would you summarize the kernel-level improvement here for the easier review?

**Comment by shtinsa** [comment]
> Thanks, @shtinsa! Would you summarize the kernel-level improvement here for the easier review?

Hello @sunggg , the discussion of performance improvements are in [this ticket](https://linear.app/octoai/issue/DEE-140/fuse-or-vectorize-scatter-output), It gives minor improvements.

**Comment by sunggg** [comment]
Yeah, I checked the ticket but had hard time to interpret the data. It seems like we see the worse performance in TTFT and ISTL but better e2e time. Would you explain what is happening? I saw there are two nsys profiles attached but any summary would be appreciated to make the review easier.

**Comment by islavutin** [comment]
@sunggg not exactly. Here is the main comment to analyze https://linear.app/octoai/issue/DEE-140/fuse-or-vectorize-scatter-output#comment-26f35a7d. We see improvements on kernel level through nvsys, but they are not too much noticable on the e2e level, so the recommendation is to go ahead with this PR based on kernel based perf data

**Comment by masahi** [comment]
Prefill time may be more susceptible to noise. I don't see anything in this code that would introduce regression.

**Comment by masahi** [comment]
@shtinsa Similar to what @echuraev did for `take` in https://github.com/octoml/ollm/pull/967, can you send this change to ollm? We try not to change our mlc fork if possible. 

Also, please revisit TTFT measurement to clear any confusion.

**Pull request closed without merging**
