### PR TITLE
[SmoothQuant] Remove unused functions

### PR DESCRIPTION
**Pull request by ibsidorenko**
This is refactoring to follow new rule: "keep mlc-llm and tvm as clean as possible".
This commit removes several helper functions that were moved to slm/interface part.

### CODE REVIEW

**Comment by ponytaill** [comment]
Hi, I tested it and I want to ask if the Smoothquant quantization really works? I run `mlc_llm convert_weight ./dist/llama2 --quantization smq_q8i8f16_0 -o dist/$llama2-smq-MLC/` and get unquantized model. Weird.

**Comment by ibsidorenko** [comment]
> Hi, I tested it and I want to ask if the Smoothquant quantization really works? I run `mlc_llm convert_weight ./dist/llama2 --quantization smq_q8i8f16_0 -o dist/$llama2-smq-MLC/` and get unquantized model. Weird.

Hi @ponytaill ! It works, but not through the mlc-llm.

**Comment by ponytaill** [comment]
> > Hi, I tested it and I want to ask if the Smoothquant quantization really works? I run `mlc_llm convert_weight ./dist/llama2 --quantization smq_q8i8f16_0 -o dist/$llama2-smq-MLC/` and get unquantized model. Weird.
> 
> Hi @ponytaill ! It works, but not through the mlc-llm.
Hi, thanks for your reply. Could you explain a little bit about how to use the code about Smoothquant without going through mlc-llm? I just started learning mlc-llm.

**Comment by ibsidorenko** [comment]
> > > Hi, I tested it and I want to ask if the Smoothquant quantization really works? I run `mlc_llm convert_weight ./dist/llama2 --quantization smq_q8i8f16_0 -o dist/$llama2-smq-MLC/` and get unquantized model. Weird.
> > 
> > 
> > Hi @ponytaill ! It works, but not through the mlc-llm.
> > Hi, thanks for your reply. Could you explain a little bit about how to use the code about Smoothquant without going through mlc-llm? I just started learning mlc-llm.

You need access to the private repo. If you don't have access, there's no way to run SmoothQuant in this case

**Pull request merged**
