### PR TITLE
Decompose sample_from_logits for clarity and further development

### PR DESCRIPTION
**Pull request by vvchernov**
- refactor of `model_common.py`: transform duplicated code in `sample_from_logits` to two additional function. It makes the function more readable and help me further for loglikelihood development.
- Add generalized type. I also plan add new Request type for loglikelihood and it is convenient to keep union of all request types in one place

### CODE REVIEW

**Comment by masahi** [comment]
Sorry the PR that added `sample_from_logits` has been reverted in https://github.com/octoml/mlc-llm/pull/189 due to a bug, I'm debugging it

**Comment by masahi** [comment]
Ok fixed by https://github.com/octoml/mlc-llm/pull/191, recommended to rebase.

**Comment by vvchernov** [comment]
Hello @masahi! please review

**Review by masahi — APPROVED** [review]

**Comment by sunggg** [comment]
Hey, @vvchernov. Thank you for the refactoring! 
I think request type of loglikelihood is interesting, but I'm unsure what benefit it can bring. 
If there are mixture of non-logprob and logprob requests, how can this benefit us? 
Currently, all the requests in the batch make progress in a lock step fashion so it is unclear to me how it can change this without significant change in the engine design. 

Also, I'm about to send the huge refactoring of sampler, so just heads-up. Probably it will be ready for review early next week.

**Comment by vvchernov** [comment]
Hello @sunggg! Thank you for the comments!
About loglikelihood request, you can see details in #69. Due to pipeline is strongly different, I also added new packed func on topology side, new request type was reasonable solution.
It should be noted that logprobs support in #82 and loglikelihood is not the same or close, though the latter uses logprob output API.
About mixture of requests with/without logprobs can be problem (I wrote about it in #82) due to logprob processing requires much time. They can be also separated to new request regime, but simultaneously it should be done in async regime [here](https://github.com/octoml/mlc-llm/blob/c36d47c1ec7b2d0f331f33d1795e3f7a1cfaf42d/serve/mlc_serve/model/paged_cache_model.py#L49C1-L65C83) or stream with different type of requests should be separated on higher level.
And last thing, where is I can follow sampler refactoring? Looks like loglikelihood feature also will be ready next week

**Comment by sunggg** [comment]
I see. Thank you for the explanation, let me follow-up with #69 as I'm not familiar with it yet. 
Here is my WIP PR: https://github.com/octoml/mlc-llm/pull/192 and I expect this will be ready by early next week. 
This aims to vectorize the sampling computation and utilize CPU to prepare sampling metadata asynchronously.

**Pull request merged**
